nome = str(input('Digite o seu nome ')).strip()
print('Analisando o seu nome...')
print('Seu nome em maiúsculas é {}'.format(nome.upper()))
print('Seu nome em minúsculas é {}'.format(nome.lower()))
print('Seu nome em tem ao todo {}'.format(len(nome) - nome.count(' ')))
separa = nome.split()
print('Seu primeiro nome tem {} letras '.format(nome.find(' ')))
print('Seu primeiro nome é {} e ele tem {} letras '.format(separa[0], len(separa[0])))